apiVersion: apps/v1
kind: Deployment
metadata:
  name: newreact-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newreact
  template:
    metadata:
      labels:
        app: newreact
    spec:
      containers:
      - name: newreact
        image: metricfrontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: newreact-service
spec:
  type: NodePort
  selector:
    app: newreact
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

